[tool.poetry]
name = "alembic-test"
version = "0.1.0"
description = ""
authors = ["Skye Im <skye.im@cognite.com>"]

[tool.poetry.dependencies]
python = "^3.8"
alembic = "^1.4.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
